package validation

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"golang.org/x/tools/go/analysis"
)

const (
	// AnalyzerName is the exposed go/analysis analyzer name.
	AnalyzerName = "anyguard"
	// DefaultAllowlistPath is the default YAML allowlist file location.
	DefaultAllowlistPath = "internal/ci/any_allowlist.yaml"
	// DefaultRoots defines the default configured roots to analyze.
	DefaultRoots = "./..."

	flagAllowlist = "allowlist"
	flagRoots     = "roots"
	flagRepoRoot  = "repo-root"

	goModFilename = "go.mod"
	goTestPkgPath = ".test"
	mainPkgName   = "main"

	errNoRootsProvided = "no roots provided for any usage validation"
)

var generatedGoTestMainHeader = []byte("// Code generated by 'go test'. DO NOT EDIT.")

// NewAnalyzer constructs a go/analysis analyzer for any-usage validation.
func NewAnalyzer() *analysis.Analyzer {
	cfg := &analyzerConfig{
		allowlistPath: DefaultAllowlistPath,
		roots:         DefaultRoots,
	}
	analyzer := &analysis.Analyzer{
		Name:             AnalyzerName,
		Doc:              "reports disallowed usage of the Go any type",
		Run:              cfg.run,
		RunDespiteErrors: true,
		ResultType:       reflect.TypeOf(analysisResult{}),
	}
	analyzer.Flags.StringVar(&cfg.allowlistPath, flagAllowlist, DefaultAllowlistPath, "path to any usage allowlist YAML")
	analyzer.Flags.StringVar(&cfg.roots, flagRoots, DefaultRoots, "comma-separated roots to scan")
	analyzer.Flags.StringVar(&cfg.repoRoot, flagRepoRoot, "", "repository root (auto-detected when empty)")
	return analyzer
}

type analyzerConfig struct {
	allowlistPath      string
	roots              string
	repoRoot           string
	loadRepoValidation func(repoValidationConfig) (repoValidationResult, error)
}

type analyzerFile struct {
	content   []byte
	relPath   string
	syntax    *ast.File
	tokenFile *token.File
}

type analyzerViolation struct {
	tokenFile *token.File
	violation Error
}

type analysisResult struct{}

func (cfg *analyzerConfig) run(pass *analysis.Pass) (any, error) {
	roots := splitRoots(cfg.roots)
	if len(roots) == 0 {
		return nil, errors.New(errNoRootsProvided)
	}

	repoRoot, err := cfg.resolveRepoRoot(pass)
	if err != nil {
		return nil, err
	}

	allowlistPath, err := resolveAllowlistPath(repoRoot, cfg.allowlistPath)
	if err != nil {
		return nil, err
	}

	buildCtx := currentBuildContext()
	validationConfig, err := loadRepoValidationConfig(repoRoot, roots, allowlistPath, buildCtx)
	if err != nil {
		return nil, err
	}

	files, err := collectAnalyzerFilesWithNormalizedRoots(
		pass,
		repoRoot,
		validationConfig.roots,
		validationConfig.excludeGlobs,
	)
	if err != nil {
		return nil, err
	}
	packageFindings, err := collectAnalyzerFindings(pass, files)
	if err != nil {
		return nil, err
	}

	// collectAnalyzerFindings builds packageFindings for current-package diagnostics,
	// while repo-wide validation is cached across analyzer passes in the same process.
	repoResult, err := cfg.loadRepoValidationResult(validationConfig)
	if err != nil {
		return nil, err
	}

	reportViolations(pass, collectAnalyzerViolations(files, packageFindings, repoResult.index))
	return analysisResult{}, nil
}

func (cfg *analyzerConfig) loadRepoValidationResult(config repoValidationConfig) (repoValidationResult, error) {
	if cfg.loadRepoValidation != nil {
		return cfg.loadRepoValidation(config)
	}
	return loadRepoValidationResult(config)
}

func (cfg *analyzerConfig) resolveRepoRoot(pass *analysis.Pass) (string, error) {
	if cfg.repoRoot != "" {
		repoRoot, err := filepath.Abs(cfg.repoRoot)
		if err != nil {
			return "", fmt.Errorf("resolve repo-root: %w", err)
		}
		return repoRoot, nil
	}

	filename := firstPassFilename(pass)
	if filename != "" {
		if root, ok := findGoModRoot(filepath.Dir(filename)); ok {
			return root, nil
		}
	}

	cwd, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("resolve working directory: %w", err)
	}
	if root, ok := findGoModRoot(cwd); ok {
		return root, nil
	}
	return cwd, nil
}

func firstPassFilename(pass *analysis.Pass) string {
	if len(pass.Files) == 0 {
		return ""
	}
	return pass.Fset.PositionFor(pass.Files[0].Package, false).Filename
}

func findGoModRoot(start string) (string, bool) {
	dir := filepath.Clean(start)
	for {
		if fileExists(filepath.Join(dir, goModFilename)) {
			return dir, true
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", false
		}
		dir = parent
	}
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}

func resolveAllowlistPath(repoRoot, configured string) (string, error) {
	if filepath.IsAbs(configured) {
		return filepath.Clean(configured), nil
	}
	path := filepath.Join(repoRoot, configured)
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", fmt.Errorf("resolve allowlist path: %w", err)
	}
	return abs, nil
}

func collectAnalyzerFiles(pass *analysis.Pass, repoRoot string, roots []string, excludeGlobs []string) ([]analyzerFile, error) {
	filteredRoots := normalizeConfiguredRoots(roots, repoRoot)
	compiledGlobs, err := compileExcludeGlobs(excludeGlobs)
	if err != nil {
		return nil, err
	}
	return collectAnalyzerFilesWithNormalizedRoots(pass, repoRoot, filteredRoots, compiledGlobs)
}

func collectAnalyzerFilesWithNormalizedRoots(
	pass *analysis.Pass,
	repoRoot string,
	filteredRoots []string,
	excludeGlobs compiledExcludeGlobs,
) ([]analyzerFile, error) {
	if len(filteredRoots) == 0 {
		return nil, errors.New("no usable roots after normalization")
	}

	files := make([]analyzerFile, 0, len(pass.Files))
	for _, file := range pass.Files {
		collected, keep, err := collectAnalyzerFile(pass, file, repoRoot, filteredRoots, excludeGlobs)
		if err != nil {
			return nil, err
		}
		if keep {
			files = append(files, collected)
		}
	}
	return files, nil
}

func collectAnalyzerFile(
	pass *analysis.Pass,
	file *ast.File,
	repoRoot string,
	roots []string,
	excludeGlobs compiledExcludeGlobs,
) (analyzerFile, bool, error) {
	pos := pass.Fset.PositionFor(file.Package, false)
	if pos.Filename == "" {
		return analyzerFile{}, false, nil
	}

	relPath, err := relativePath(repoRoot, pos.Filename)
	if err != nil {
		if shouldIgnoreGeneratedGoTestMain(pass, pos.Filename) {
			return analyzerFile{}, false, nil
		}
		return analyzerFile{}, false, fmt.Errorf("compute relative path for %s: %w", pos.Filename, err)
	}
	if !shouldCollectAnalyzerPath(relPath, roots, excludeGlobs) {
		return analyzerFile{}, false, nil
	}

	tokenFile := pass.Fset.File(file.Package)
	if tokenFile == nil {
		return analyzerFile{}, false, nil
	}

	content, err := readAnalyzerFile(pass, pos.Filename)
	if err != nil {
		return analyzerFile{}, false, fmt.Errorf("read analyzer file %s: %w", pos.Filename, err)
	}
	return analyzerFile{
		content:   content,
		relPath:   relPath,
		syntax:    file,
		tokenFile: tokenFile,
	}, true, nil
}

func shouldCollectAnalyzerPath(relPath string, roots []string, excludeGlobs compiledExcludeGlobs) bool {
	return isWithinRoots(relPath, roots) && !shouldExclude(relPath, excludeGlobs)
}

func readAnalyzerFile(pass *analysis.Pass, filename string) ([]byte, error) {
	if pass.ReadFile != nil {
		return pass.ReadFile(filename)
	}
	// #nosec G304 -- filename comes from analysis pass file metadata.
	return os.ReadFile(filename)
}

func shouldIgnoreGeneratedGoTestMain(pass *analysis.Pass, filename string) bool {
	if pass.Pkg == nil || pass.Pkg.Name() != mainPkgName || !strings.HasSuffix(pass.Pkg.Path(), goTestPkgPath) {
		return false
	}

	content, err := readAnalyzerFile(pass, filename)
	if err != nil {
		return false
	}
	return bytes.HasPrefix(bytes.TrimLeft(content, "\ufeff\r\n\t "), generatedGoTestMainHeader)
}

func collectAnalyzerFindings(pass *analysis.Pass, files []analyzerFile) ([]collectedFinding, error) {
	if len(files) == 0 {
		return nil, nil
	}

	resolver := newLexicalAnyResolver(analyzerResolverFiles(pass, files))
	findings := make([]collectedFinding, 0)
	for _, file := range files {
		findings = append(findings, collectParsedFileFindings(pass.Fset, resolver, parsedGoFile{
			relPath: file.relPath,
			content: file.content,
			syntax:  file.syntax,
		})...)
	}
	sortCollectedFindings(findings)
	return findings, nil
}

func analyzerResolverFiles(pass *analysis.Pass, files []analyzerFile) []*ast.File {
	if len(pass.Files) > 0 {
		return pass.Files
	}

	syntaxFiles := make([]*ast.File, 0, len(files))
	for _, file := range files {
		syntaxFiles = append(syntaxFiles, file.syntax)
	}
	return syntaxFiles
}

func relativePath(repoRoot, absPath string) (string, error) {
	relPath, err := filepath.Rel(repoRoot, absPath)
	if err != nil {
		return "", fmt.Errorf("cannot establish canonical repository-relative path: %w", err)
	}
	normalized := normalizePath(relPath)
	if normalized == "" || isEscapingPath(normalized) {
		return "", fmt.Errorf(
			"cannot establish canonical repository-relative path for %s under repo root %s",
			filepath.Clean(absPath),
			filepath.Clean(repoRoot),
		)
	}
	return normalized, nil
}

func isEscapingPath(path string) bool {
	return path == ".." || strings.HasPrefix(path, "../")
}

func normalizeConfiguredRoots(roots []string, repoRoot string) []string {
	normalized := make([]string, 0, len(roots))
	for _, root := range roots {
		root = normalizeRootValue(root)
		if root == "" {
			continue
		}
		if filepath.IsAbs(root) {
			rel, err := filepath.Rel(repoRoot, root)
			if err != nil {
				continue
			}
			root = rel
		}
		root = normalizePath(root)
		if root == "" {
			root = "."
		}
		normalized = append(normalized, root)
	}
	return normalized
}

func isWithinRoots(relPath string, roots []string) bool {
	for _, root := range roots {
		if root == "." {
			return true
		}
		if relPath == root || strings.HasPrefix(relPath, root+"/") {
			return true
		}
	}
	return false
}

func splitRoots(value string) []string {
	value = strings.TrimSpace(value)
	if value == "" {
		return nil
	}

	parts := strings.Split(value, ",")
	roots := make([]string, 0, len(parts))
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part != "" {
			roots = append(roots, part)
		}
	}
	if len(roots) == 0 {
		return nil
	}
	return roots
}

func collectAnalyzerViolations(files []analyzerFile, findings []collectedFinding, index anyAllowlistIndex) []analyzerViolation {
	if len(files) == 0 || len(findings) == 0 {
		return nil
	}

	tokenFilesByPath := make(map[string]*token.File, len(files))
	filteredFindings := make([]collectedFinding, 0, len(findings))
	for _, file := range files {
		tokenFilesByPath[file.relPath] = file.tokenFile
	}

	for _, finding := range findings {
		if _, ok := tokenFilesByPath[finding.identity.File]; !ok {
			continue
		}
		filteredFindings = append(filteredFindings, finding)
	}

	violations := violationsFromFindings(filteredFindings, index)
	reportable := make([]analyzerViolation, 0, len(violations))
	for _, violation := range violations {
		reportable = append(reportable, analyzerViolation{
			tokenFile: tokenFilesByPath[violation.File],
			violation: violation,
		})
	}
	return reportable
}

func reportViolations(pass *analysis.Pass, violations []analyzerViolation) {
	for _, reportable := range violations {
		reportViolation(pass, reportable.tokenFile, reportable.violation)
	}
}

func reportViolation(pass *analysis.Pass, file *token.File, violation Error) {
	if file == nil {
		return
	}

	pos, ok := violationPos(file, violation.Line, violation.Column)
	if !ok {
		return
	}

	message := violation.Message
	if violation.Code != "" {
		message = message + " (code: " + violation.Code + ")"
	}

	pass.Report(analysis.Diagnostic{
		Pos:     pos,
		End:     lineEnd(file, violation.Line, pos),
		Message: message,
	})
}

func violationPos(file *token.File, line, column int) (token.Pos, bool) {
	if line <= 0 || line > file.LineCount() {
		return token.NoPos, false
	}

	start := file.LineStart(line)
	if column <= 1 {
		return start, true
	}

	pos := start + token.Pos(column-1)
	end := lineEnd(file, line, start)
	if pos > end {
		return end, true
	}
	return pos, true
}

func lineEnd(file *token.File, line int, pos token.Pos) token.Pos {
	if line < file.LineCount() {
		nextLineStart := file.LineStart(line + 1)
		if nextLineStart > pos {
			return nextLineStart - 1
		}
	}

	if size := file.Size(); size > 0 {
		end := file.Pos(size)
		if end > pos {
			return end
		}
	}

	return pos
}
